# Generated by Django 3.0.8 on 2020-08-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_link', models.TextField()),
                ('news_text', models.TextField()),
                ('output', models.TextField()),
            ],
        ),
    ]
