# Generated by Django 3.1 on 2020-08-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField(default=' ')),
                ('news_link', models.TextField(default=' ')),
                ('news_title', models.TextField(default=' ')),
                ('news_text', models.TextField(default=' ')),
                ('output', models.TextField(default=' ')),
            ],
        ),
    ]
