# Generated by Django 3.0.8 on 2020-08-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsinfo',
            name='news_title',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='newsinfo',
            name='news_link',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='newsinfo',
            name='news_text',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='newsinfo',
            name='output',
            field=models.TextField(default=' '),
        ),
    ]
